### ISSUE TITLE
Immediate to-do's

### ISSUE THREAD

**Issue by rayoowoo** [rayoowoo/chess#1]
- [ ] change board.move_piece to have the same logic as board.move_piece!
- [ ] implement cursor moving pieces
- [ ] refactor refactor refactor
